# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170413_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
