# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170428_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_s', models.TextField(blank=True)),
                ('msg_r', models.TextField(blank=True)),
                ('msg_pk', models.IntegerField(blank=True)),
                ('btns', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('response_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.User')),
            ],
        ),
    ]
